---
- name: create deployment directory
  file:
    path: '{{ DEPLOYMENT_ROOT }}'
    state: directory
    mode: 0755

- name: copy docker-compose.yml
  copy:
    src: docker-compose.yml
    dest: '{{ DEPLOYMENT_ROOT }}/docker-compose.yml'
    owner: root
    group: root
    mode: 0644

- name: generate .env
  blockinfile:
    path: '{{ DEPLOYMENT_ROOT }}/.env'
    create: yes
    owner: root
    group: root
    mode: 0644
    block: |
      DEPLOYMENT_ROOT={{ DEPLOYMENT_ROOT }}

      FINANCE_GO_CRAWLER_IMAGE={{ FINANCE_GO_CRAWLER_IMAGE }}
      FINANCE_GO_PROCESSOR_IMAGE={{ FINANCE_GO_PROCESSOR_IMAGE }}
      FINANCE_GO_ANALYZER_IMAGE={{ FINANCE_GO_ANALYZER_IMAGE }}
      FINANCE_GO_SHIELDER_IMAGE={{ FINANCE_GO_SHIELDER_IMAGE }}
      FINANCE_GO_PORTER_IMAGE={{ FINANCE_GO_PORTER_IMAGE }}
      FINANCE_REACT_HUNTER_IMAGE={{ FINANCE_REACT_HUNTER_IMAGE }}

      ENVIRONMENT={{ ENVIRONMENT }}
      DIRECTORY_BASE={{ DIRECTORY_BASE }}
      DIRECTORY_LOG={{ DIRECTORY_LOG }}
      DIRECTORY_DATA={{ DIRECTORY_DATA }}
      CASSANDRA_HOSTS={{ CASSANDRA_HOSTS }}
      CASSANDRA_KEYSPACE={{ CASSANDRA_KEYSPACE }}
      KAFKA_BOOTSTRAP_SERVERS={{ KAFKA_BOOTSTRAP_SERVERS }}
      CRAWLER_MODE={{ CRAWLER_MODE }}

      TWSE_DATA={{ TWSE_DATA }}
      TWSE_CRON={{ TWSE_CRON }}

      SHIELDER_HOST={{ SHIELDER_HOST }}
      SHIELDER_PORT={{ SHIELDER_PORT }}
      SHIELDER_CORS_METHODS={{ SHIELDER_CORS_METHODS }}
      SHIELDER_CORS_ORIGINS={{ SHIELDER_CORS_ORIGINS }}

      PORTER_V1_HOST={{ PORTER_V1_HOST }}
      PORTER_V1_PORT={{ PORTER_V1_PORT }}

      HUNTER_PORT={{ HUNTER_PORT }}

      SHIELDER_PROXY_SCHEME={{ SHIELDER_PROXY_SCHEME }}
      SHIELDER_PROXY_HOST={{ SHIELDER_PROXY_HOST }}
      SHIELDER_PROXY_PORT={{ SHIELDER_PROXY_PORT }}

- name: create finance directories
  file:
    path: '{{ item }}'
    state: directory
    mode: 0777
  with_items:
    - '{{ DIRECTORY_BASE }}'
    - '{{ DIRECTORY_BASE }}{{ DIRECTORY_LOG }}'
    - '{{ DIRECTORY_BASE }}{{ DIRECTORY_DATA }}'
    - '{{ DIRECTORY_BASE }}{{ DIRECTORY_DATA }}{{ TWSE_DATA }}'

- name: pull docker images
  command: /usr/local/bin/docker-compose pull
  args:
    chdir: '{{ DEPLOYMENT_ROOT }}'

- name: start docker
  command: /usr/local/bin/docker-compose up -d
  args:
    chdir: '{{ DEPLOYMENT_ROOT }}'
