version: "3"
services:
  finance-go-crawler:
    image: ${FINANCE_GO_CRAWLER_IMAGE}
    volumes:
      - "${DIRECTORY_CONFIG}:${DIRECTORY_CONFIG}:ro,z"
      - "${DIRECTORY_LOG}:${DIRECTORY_LOG}:z"
      - "${DIRECTORY_DATA}:${DIRECTORY_DATA}:z"
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - DIRECTORY_BASE=${DIRECTORY_BASE}
      - DIRECTORY_CONFIG=${DIRECTORY_CONFIG}
      - DIRECTORY_LOG=${DIRECTORY_LOG}
      - DIRECTORY_DATA=${DIRECTORY_DATA}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - CRAWLER_MODE=${CRAWLER_MODE}
      - CRAWLER_DAEMON_CRON=${CRAWLER_DAEMON_CRON}
    restart: always
  finance-go-processor:
    image: ${FINANCE_GO_PROCESSOR_IMAGE}
    volumes:
      - "${DIRECTORY_CONFIG}:${DIRECTORY_CONFIG}:ro,z"
      - "${DIRECTORY_LOG}:${DIRECTORY_LOG}:z"
      - "${DIRECTORY_DATA}:${DIRECTORY_DATA}:ro,z"
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - DIRECTORY_BASE=${DIRECTORY_BASE}
      - DIRECTORY_CONFIG=${DIRECTORY_CONFIG}
      - DIRECTORY_LOG=${DIRECTORY_LOG}
      - DIRECTORY_DATA=${DIRECTORY_DATA}
      - CASSANDRA_HOSTS=${CASSANDRA_HOSTS}
      - CASSANDRA_KEYSPACE=${CASSANDRA_KEYSPACE}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
    restart: always
  finance-go-analyzer:
    image: ${FINANCE_GO_ANALYZER_IMAGE}
    volumes:
      - "${DIRECTORY_CONFIG}:${DIRECTORY_CONFIG}:ro,z"
      - "${DIRECTORY_LOG}:${DIRECTORY_LOG}:z"
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - DIRECTORY_BASE=${DIRECTORY_BASE}
      - DIRECTORY_CONFIG=${DIRECTORY_CONFIG}
      - DIRECTORY_LOG=${DIRECTORY_LOG}
      - CASSANDRA_HOSTS=${CASSANDRA_HOSTS}
      - CASSANDRA_KEYSPACE=${CASSANDRA_KEYSPACE}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
    restart: always
