version: "3"
services:
  finance-go-crawler:
    image: ${FINANCE_GO_CRAWLER_IMAGE}
    volumes:
      - "${DIRECTORY_BASE_PREFIX}_${ENVIRONMENT_NAME}${DIRECTORY_LOG}:${DIRECTORY_BASE_PREFIX}_${ENVIRONMENT_NAME}${DIRECTORY_LOG}:z"
      - "${DIRECTORY_BASE_PREFIX}_${ENVIRONMENT_NAME}${DIRECTORY_DATA}:${DIRECTORY_BASE_PREFIX}_${ENVIRONMENT_NAME}${DIRECTORY_DATA}:z"
    environment:
      - ENVIRONMENT_NAME=${ENVIRONMENT_NAME}
      - DIRECTORY_BASE_PREFIX=${DIRECTORY_BASE_PREFIX}
      - DIRECTORY_LOG=${DIRECTORY_LOG}
      - DIRECTORY_DATA=${DIRECTORY_DATA}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - CRAWLER_MODE=${CRAWLER_MODE}
      - TWSE_DATA=${TWSE_DATA}
      - TWSE_CRON=${TWSE_CRON}
    restart: always
  finance-go-processor:
    image: ${FINANCE_GO_PROCESSOR_IMAGE}
    volumes:
      - "${DIRECTORY_BASE_PREFIX}_${ENVIRONMENT_NAME}${DIRECTORY_LOG}:${DIRECTORY_BASE_PREFIX}_${ENVIRONMENT_NAME}${DIRECTORY_LOG}:z"
      - "${DIRECTORY_BASE_PREFIX}_${ENVIRONMENT_NAME}${DIRECTORY_DATA}:${DIRECTORY_BASE_PREFIX}_${ENVIRONMENT_NAME}${DIRECTORY_DATA}:ro,z"
    environment:
      - ENVIRONMENT_NAME=${ENVIRONMENT_NAME}
      - DIRECTORY_BASE_PREFIX=${DIRECTORY_BASE_PREFIX}
      - DIRECTORY_LOG=${DIRECTORY_LOG}
      - DIRECTORY_DATA=${DIRECTORY_DATA}
      - CASSANDRA_HOSTS=${CASSANDRA_HOSTS}
      - CASSANDRA_KEYSPACE_PREFIX=${CASSANDRA_KEYSPACE_PREFIX}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
    restart: always
  finance-go-analyzer:
    image: ${FINANCE_GO_ANALYZER_IMAGE}
    volumes:
      - "${DIRECTORY_BASE_PREFIX}_${ENVIRONMENT_NAME}${DIRECTORY_LOG}:${DIRECTORY_BASE_PREFIX}_${ENVIRONMENT_NAME}${DIRECTORY_LOG}:z"
    environment:
      - ENVIRONMENT_NAME=${ENVIRONMENT_NAME}
      - DIRECTORY_BASE_PREFIX=${DIRECTORY_BASE_PREFIX}
      - DIRECTORY_LOG=${DIRECTORY_LOG}
      - CASSANDRA_HOSTS=${CASSANDRA_HOSTS}
      - CASSANDRA_KEYSPACE_PREFIX=${CASSANDRA_KEYSPACE_PREFIX}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
    restart: always
  finance-go-porter:
    image: ${FINANCE_GO_PORTER_IMAGE}
    ports:
      - ${PORTER_V1_PORT}:${PORTER_V1_PORT}
    volumes:
      - "${DIRECTORY_BASE_PREFIX}_${ENVIRONMENT_NAME}${DIRECTORY_LOG}:${DIRECTORY_BASE_PREFIX}_${ENVIRONMENT_NAME}${DIRECTORY_LOG}:z"
    environment:
      - ENVIRONMENT_NAME=${ENVIRONMENT_NAME}
      - DIRECTORY_BASE_PREFIX=${DIRECTORY_BASE_PREFIX}
      - DIRECTORY_LOG=${DIRECTORY_LOG}
      - CASSANDRA_HOSTS=${CASSANDRA_HOSTS}
      - CASSANDRA_KEYSPACE_PREFIX=${CASSANDRA_KEYSPACE_PREFIX}
      - PORTER_V1_PORT=${PORTER_V1_PORT}
    restart: always
  finance-go-shielder:
    image: ${FINANCE_GO_SHIELDER_IMAGE}
    ports:
      - ${SHIELDER_PORT}:${SHIELDER_PORT}
    volumes:
      - "${DIRECTORY_BASE_PREFIX}_${ENVIRONMENT_NAME}${DIRECTORY_LOG}:${DIRECTORY_BASE_PREFIX}_${ENVIRONMENT_NAME}${DIRECTORY_LOG}:z"
    environment:
      - ENVIRONMENT_NAME=${ENVIRONMENT_NAME}
      - DIRECTORY_BASE_PREFIX=${DIRECTORY_BASE_PREFIX}
      - DIRECTORY_LOG=${DIRECTORY_LOG}
      - SHIELDER_PORT=${SHIELDER_PORT}
      - SHIELDER_CORS_METHODS=${SHIELDER_CORS_METHODS}
      - SHIELDER_CORS_ORIGINS=${SHIELDER_CORS_ORIGINS}
      - PORTER_V1_HOST=${PORTER_V1_HOST}
      - PORTER_V1_PORT=${PORTER_V1_PORT}
    restart: always
  finance-react-hunter:
    image: ${FINANCE_REACT_HUNTER_IMAGE}
    ports:
      - ${HUNTER_PORT}:${HUNTER_PORT}
    environment:
      - ENVIRONMENT_NAME=${ENVIRONMENT_NAME}
      - HUNTER_PORT=${HUNTER_PORT}
      - SHIELDER_PROXY_SCHEME=${SHIELDER_PROXY_SCHEME}
      - SHIELDER_PROXY_HOST=${SHIELDER_PROXY_HOST}
      - SHIELDER_PROXY_PORT=${SHIELDER_PROXY_PORT}
    restart: always
