version: "2"
services:
  postgres:
    image: postgres:${POSTGRES_TAG}
    ports:
      - 35432:5432
    volumes:
      - "postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
  cassandra:
    image: cassandra:${CASSANDRA_TAG}
    ports:
      - 39042:9042
    volumes:
      - "cassandra:/var/lib/cassandra"
    restart: always
  zookeeper:
    image: confluentinc/cp-zookeeper:${KAFKA_TAG}
    network_mode: "host"
    volumes:
      - "zookeeper:/var/lib/zookeeper/data"
    environment:
      - ZOOKEEPER_CLIENT_PORT=32181
    restart: always
  kafka:
    image: confluentinc/cp-kafka:${KAFKA_TAG}
    network_mode: "host"
    depends_on:
      - zookeeper
    volumes:
      - "kafka:/var/lib/kafka/data"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=${HOST_IP}:32181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${HOST_IP}:39092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    restart: always
volumes:
  postgres:
  cassandra:
  zookeeper:
  kafka:

